var fs = require('fs');
var exec = require('child-process-promise').exec;
var Promise = require('bluebird');

var gitPromises = [exec('git log --max-count=1'), exec('git reflog --decorate -1')];

Promise.all(gitPromises).then( function (promiseValues) {
  var log = promiseValues[0].stdout;
  var reflog = promiseValues[1].stdout;

  var commitId = log.match(/commit\s([a-zA-Z0-9\-.]+)/i);
      commitId = commitId ? commitId[1] : '';

  var commitDate = log.match(/Date: \s+(.*)/i);
      commitDate = commitDate ? commitDate[1] : '';

  var commidIdAbbrev = reflog.match(/^([a-z0-9]+)\s/i);
      commidIdAbbrev = commidIdAbbrev ? commidIdAbbrev[1] : '';

  var tag = reflog.match(/tag\:\s[a-zA-Z0-9\-\.]+\,/g);
      tag = tag ? tag[1] : '';

  var branch = reflog.match(/\(HEAD, (.[^)]*)\)/i);
      branch = branch ? branch[1] : '';

  var commitMessage = log.match(/^(?!Author|Date)\s+(.*)/im );
      commitMessage = commitMessage ? commitMessage[1].replace('\n', '_') : '';
  var nowDate = new Date();
  var localDateStr = nowDate.toLocaleString() + " GMT"+  (nowDate.getTimezoneOffset()>0?"-":"+") + (nowDate.getTimezoneOffset()/-60);
  var gitProperties = {
    '# Generated by': 'node-git-properties',
    '# repo': 'https://github.com/cslinmiso/node-git-properties',
    'Generate Date(Local)': localDateStr,
    'Generate Date(GMT)': nowDate.toUTCString(),
    'git.branch': branch,
    'git.tag.name': tag,
    'git.cloest.commit.id.abbrev': commidIdAbbrev,
    'git.cloest.commit.id': commitId,
    'git.cloest.commit.date': commitDate,
    'git.cloest.commit.message': commitMessage
  };

  var returnInfo = Object.keys(gitProperties).map(function(key, idx){
    return key + ': ' + gitProperties[key] + '\n';
  })

  // Generate git.properties file
  fs.writeFile('git.properties', returnInfo.join(''), function(err){
    if(err) {
      console.log('[node-git-properties][ERROR]: can\'t create git.properties file.');
    }else{
      console.log('[node-git-properties] git.properties has successfully created.');
    }
  });

}).catch ( function (error) {
    console.log('[node-git-properties][ERROR]: ', error);
    process.exit(1);
});
